server.port: 56002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: spring
    password: “@hello72”
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: update